version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能
    container_name: app
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/src
    working_dir: "/src"